#!/bin/bash

set -e -u -o pipefail

package=github.com/hansmi/cocoon

docker run --rm \
  --user "$(id -u):$(id -g)" \
  --env HOME=/tmp \
  -v "${PWD}:/go/src/${package}" \
  -w "/go/src/${package}" \
  goreleaser/goreleaser:latest release --snapshot --clean --skip=publish

# vim: set sw=2 sts=2 et :
