# Configuration for GoReleaser
# https://goreleaser.com/
#
# Local test: contrib/build-all
#

version: 2

project_name: cocoon

builds:
  - main: .
    binary: cocoon
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    flags:
      - -trimpath
    ldflags: |
      -s -w

nfpms:
  - description: Run command in container while preserving local execution environment
    maintainer: M. Hanselmann
    bindir: /usr/bin
    license: BSD-3-Clause
    formats:
      - deb
      - rpm
    contents:
      - src: ./README.md
        dst: /usr/share/doc/cocoon/README.md
      - src: ./LICENSE
        dst: /usr/share/doc/cocoon/LICENSE

archives:
  - format: tar.gz
    wrap_in_directory: true
    files:
      - LICENSE
      - README.md

release:
  draft: true
  prerelease: auto

snapshot:
  name_template: '{{ incpatch .Version }}-snapshot{{ replace (replace .Date ":" "") "-" "" }}+g{{ .ShortCommit }}'

# vim: set sw=2 sts=2 et :
