// Code generated by "stringer -type=mountMode -linecomment -output=mount_string.go"; DO NOT EDIT.

package main

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[mountReadOnly-0]
	_ = x[mountReadWrite-1]
}

const _mountMode_name = "rorw"

var _mountMode_index = [...]uint8{0, 2, 4}

func (i mountMode) String() string {
	if i < 0 || i >= mountMode(len(_mountMode_index)-1) {
		return "mountMode(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _mountMode_name[_mountMode_index[i]:_mountMode_index[i+1]]
}
